# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  #adapter: sqlite3 # SQLite 
  adapter: mysql2
  encoding: utf8mb4
#  database: accounting_system
  username: root
  password: 75917591
  host: 127.0.0.1
  port: 8889
  pool: 5

  
  
development:
  <<: *default
  database: accounting_system

test:
  <<: *default
  database: accounting_system

production:
  <<: *default
  database: your_app_production
  username: prod_user       # 可選：正式環境可用不同帳號
  password: prod_password   # 可選：正式環境密碼
  host: db.example.com      # 可選：正式環境資料庫主機